Minor updates to git pre-commit hook (#427)
* Use echo, not @echo

@echo is Makefile syntax, not bash

* Make formatters configurable

e.g., one may want to use clang-format-3.8, not just clang-format

* Add description how to bypass format checker

for dummies like me

* Do not collect filenames repeatedly

* Add a space for the prompt :-)

* Fix issue with "staging-bypass" commits

* Fix issue with partial staging of files

* Show colored diff output

* Add missing line separator between files in patch

* Add comment for non-default-index failure

diff --git a/.hooks/pre-commit b/.hooks/pre-commit
--- a/.hooks/pre-commit
+++ b/.hooks/pre-commit
@@ -1,9 +1,9 @@
 #!/bin/bash
-#
-CXX_FORMAT="clang-format"
-CXX_EXTS=".c .h .cpp .hpp .cc .hh .cxx .hxx"
 
-PY_FORMAT="autopep8"
+: ${CXX_FORMAT:=clang-format}
+: ${PY_FORMAT:=autopep8}
+
+CXX_EXTS=".c .h .cpp .hpp .cc .hh .cxx .hxx"
 PY_EXTS=".py"
 
 command_exists() {
@@ -19,51 +19,76 @@ match_extension() {
 	return 1
 }
 
-show_patch() {
-	local diff=""
-	for file in `git diff-index --cached --name-only HEAD` ; do
+get_patch() {
+	local reformatted=""
+	local file
+	patch=""
+
+	for file in $files; do
 		if match_extension $file "$CXX_EXTS"; then
-			diff+=$($CXX_FORMAT -style=file $file | diff -u $file - | \
-				sed -e "1s|--- |--- a/|" -e "2s|+++ -|+++ b/$file|")
+			reformatted=`$CXX_FORMAT -style=file $file`
 		elif match_extension $file "$PY_EXTS"; then
-			diff+=$($PY_FORMAT $file | diff -u $file - | \
-				sed -e "1s|--- |--- a/|" -e "2s|+++ -|+++ b/$file|")
+			reformatted=`$PY_FORMAT $file`
+		else
+			continue
 		fi
+
+		# show colored version to the user
+		echo "$reformatted" | git diff --no-index --color=always $file -
+
+		# ... and save non-colored patch for git-apply
+		patch+=`echo "$reformatted" | diff -u $file - | \
+			sed -e "1s|--- |--- a/|" -e "2s|+++ -|+++ b/$file|"`
+		patch+=$'\n'
 	done
-	echo "$diff"
 }
 
-refresh_commit() {
-	for file in `git diff-index --cached --name-only HEAD` ; do
-		git add $file
-	done
+apply_and_commit() {
+	# The "git add" we use below do not work with non-default index file,
+	# which is used by "git commit -a" or "git commit <files>"
+	if [[ $GIT_INDEX_FILE != ".git/index" ]]; then
+		echo "Error: Non-default index file is being used (GIT_INDEX_FILE is set)." >&2
+		echo "       Are you using 'git commit [--only] -- <files>' to bypass staging?" >&2
+		exit 1
+	fi
+
+	# Do some files have partial commits? (only some portion of a file is staged)
+	if [[ ! -z $(git diff -- $files) ]]; then
+		echo "Error: Partial commits are not supported." >&2
+		exit 1
+	fi
+
+	(echo "$patch" | git apply -)
+	git add -- $files
 }
 
 if ! command_exists $CXX_FORMAT; then
-	echo "Error: $CXX_FORMAT executable not found.\n" >&2
+	echo "Error: '$CXX_FORMAT' not found." >&2
+	echo "       Use '--no-verify' to bypass format checker (not recommended)" >&2
 	exit 1
 fi
 
 if ! command_exists $PY_FORMAT; then
-	echo "Error: $PY_FORMAT executable not found. Try 'pip install $PY_FORMAT'?\n" >&2
+	echo "Error: '$PY_FORMAT' not found. Try 'pip install $PY_FORMAT'?" >&2
+	echo "       Use '--no-verify' to bypass format checker (not recommended)" >&2
 	exit 1
 fi
 
 # Allows us to read user input below, assigns stdin to keyboard
 exec < /dev/tty
 
-patch=$(show_patch)
+files=`git diff-index --cached --name-only HEAD`
+get_patch
 if [[ ! -z $patch ]]; then
-	echo "$patch"
 	echo "==========================================="
 	echo "Files in the commit do not comply with the formatting rules. Options:"
 	echo "y - commit without reformatting (not recommended)"
 	echo "r - apply the patch and commit"
 	echo "n - abort"
-	read -p "Do you want to commit anyway? [y/r/N]" yn
+	read -p "Do you want to commit anyway? [y/r/N] " yn
 	case $yn in
 		[Yy]* ) exit 0;;
-		[Rr]* ) (echo "$patch" | git apply -) && refresh_commit && exit 0;;
+		[Rr]* ) apply_and_commit && exit 0;;
 		* ) exit 1;;
 	esac
 fi
